name: auto_validating_text_field
description: To validate text field as soon as its value changes. We can add list of validators for different cases and it shows error message depending upon the conditions unsatisfied.
version: 0.1.1
homepage: https://github.com/rmsh03dhj/auto_validating_text_field.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
